version: '2'

services:

  mysql:
    container_name: mysql
    image: debezium/example-mysql
    ports:
    - "3306:3306"
    environment:
    - "MYSQL_ROOT_PASSWORD=debezium"
    - "MYSQL_USER=mysqluser"
    - "MYSQL_PASSWORD=mysqlpw"
